sonar.projectKey=MithrilAddons_discord
sonar.organization=mithriladdons
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12,3.13,3.14
sonar.sources=src,tools,deploy,contracts,.github,docs
sonar.tests=tests
sonar.python.coverage.reportPaths=build/reports/coverage/python.xml
sonar.python.xunit.reportPath=build/reports/python.xml
